from selenium import webdriver

driver=webdriver.Chrome(executable_path="C:/Users/shaik/PycharmProjects/drivers/chromedriver_win32/chromedriver.exe")
driver.get("http://www.amazon.com/")
coockies=driver.get_cookies()
print("number of coockies are :",len(coockies))
print(coockies)
mycoocky={"name":"mycoocky","value":"1235643"}
driver.add_cookie(mycoocky)
coockies=driver.get_cookies()
print("Now, number of coockies after adding 1 more coockyare :",len(coockies))
print(coockies)
driver.delete_cookie(mycoocky)
driver.get("http://www.amazon.com/")
driver.refresh()
coockies=driver.get_cookies()
print("After deleting 1 coocky ,number of coockies are :",len(coockies))
print(coockies)
driver.delete_all_cookies()
driver.get("http://www.amazon.com/")
driver.refresh()
coockies=driver.get_cookies()
print("After deleting all teh coockies, number of coockies are :",len(coockies))
print(coockies)
driver.refresh()
coockies=driver.get_cookies()
print("After deleting all teh coockies, number of coockies are :",len(coockies))
print(coockies)
driver.quit()